### ISSUE TITLE
Block height out of range

### ISSUE THREAD

**Issue by abrkn** [abrkn/sideshift#56]
```
2018-11-25T08:30:50.231585+00:00 app[worker.1]: Status: Scanned=551436; Node=551437; Node headers=551437
2018-11-25T08:30:50.540018+00:00 app[worker.1]: Scanning block at height 551437, 000000000000000000161166ab31bf0ed196cecc7f899abb982758fc6d0aaaaf...
2018-11-25T08:30:50.924354+00:00 app[worker.1]: Scanning 219 txs...
2018-11-25T08:30:51.237661+00:00 app[worker.1]: Scanned 2/219, 0%
2018-11-25T08:30:58.606475+00:00 app[worker.1]: Processed block at height 551437.
2018-11-25T08:30:59.238597+00:00 app[worker.1]: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2018-11-25T08:30:59.238734+00:00 app[worker.1]: Error: Block height out of range
2018-11-25T08:30:59.238786+00:00 app[worker.1]: at /app/node_modules/bitcoin/lib/jsonrpc.js:130:19
2018-11-25T08:30:59.238791+00:00 app[worker.1]: at Array.forEach (<anonymous>)
2018-11-25T08:30:59.238874+00:00 app[worker.1]: at IncomingMessage.<anonymous> (/app/node_modules/bitcoin/lib/jsonrpc.js:127:15)
2018-11-25T08:30:59.238876+00:00 app[worker.1]: at IncomingMessage.emit (events.js:185:15)
2018-11-25T08:30:59.238878+00:00 app[worker.1]: at endReadableNT (_stream_readable.js:1101:12)
2018-11-25T08:30:59.238880+00:00 app[worker.1]: at args.(anonymous function) (/app/node_modules/event-loop-inspector/index.js:138:29)
2018-11-25T08:30:59.238888+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:114:19)

=```

**Comment by abrkn** [comment]
Maybe a re-org?
